### ISSUE TITLE
EP1 Issue: Need to click Submit twice when clearing the form validation error

### ISSUE THREAD

**Issue by bernardphua** [EdCharbeneau/BlazorPowerHour#1]
Referring to EP1, noticed that you need to click Submit twice in order to trigger the OnValidSubmit event when there is a form validation error. To reproduce this scenario, click submit without filling First Name and Last Name. Form validation occurs and error message is shown. Now fill in the First Name and Last Name, and click Submit button. This will not trigger the "HandleValidSubmit" method unless you click again.

Is there a way to avoid this issue?

**1. Click submit button without filling anything.**
![image](https://user-images.githubusercontent.com/46226572/98005341-e20f1b80-1e2b-11eb-84f8-3a45156587fc.png)

**2. Fill up the 2 fields to resolve the error and click Submit. But OnValidSubmit event not trigger.**
![image](https://user-images.githubusercontent.com/46226572/98005437-fe12bd00-1e2b-11eb-8c09-9da886a269e8.png)

**3.  Click the Submit button again. This time it trigger the OnValidSubmit event.**
![image](https://user-images.githubusercontent.com/46226572/98005487-0b2fac00-1e2c-11eb-8b37-4e28fd8755be.png)

**Comment by EdCharbeneau** [comment]
What browser are you using? I can't seem to reproduce this.

As soon as move out of the text box, the validation clears and I can submit the first time.

Using Chrome.

**Comment by bernardphua** [comment]
I'm using Google Chrome browser. 

When you move out of the text box by clicking the Submit button, the validation clears but the submit event is not triggered. You need to click one more time to fire the submit event.

**Comment by SQL-MisterMagoo** [comment]
This is really just a shifting elements issue - the Submit button is moving when the validation messages are cleared.

If you move the ValidationSummary after the button, problem is solved : https://blazorrepl.com/repl/QkbvaewR52rCN44b59

**Comment by SQL-MisterMagoo** [comment]
And if you want "oninput" with InputText, you _can (if you want)_  just use some old school inline JS...

``` html
<InputText id="firstNameInput" @bind-Value="myForm.FirstName" class="form-control" 
  oninput="this.dispatchEvent(new Event('change'))">
</InputText>
```

Like this:
https://blazorrepl.com/repl/GYvlOfEa039PqJCW31

**Comment by bernardphua** [comment]
@SQL-MisterMagoo Thanks for the solution. Issue is resolved.
